config/routes.rb
Rails.application.routes.draw do
  root :to => 'stations#index'
  resources :stations
  resources :lines
  resources :stops
end

app/models/line.rb
class Line < ActiveRecord::Base
  has_many :stops
  has_many :stations, through: :stops
  validates :name, presence: true
end

app/models/station.rb
class Station < ActiveRecord::Base
  has_many :stops
  has_many :lines, through: :stops
  validates :name, presence: true
end

app/models/stop.rb
class Stop < ActiveRecord::Base
  belongs_to :line
  belongs_to :station
  before_validation :time_form
  validates :time, presence: true

  def find_station
    Station.find(self.station_id)
  end

  def find_line
    Line.find(self.line_id)
  end

private
  def time_form
    m = /(\d{1,2}:\d{1,2})/.match(self.time)
    if m == nil
      self.time = nil
    else
      self.time = m[0]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  def index
    @lines = Line.all
  end

  def new
    @line = Line.new
  end

  def create
    @line = Line.new(line_params)
    if @line.save
      flash[:notice] = "Line created."
      redirect_to lines_path
    else
      render 'new'
    end
  end

  def show
    @line = Line.find(params[:id])
    @stops = Stop.where(line_id: @line.id)
  end

  def edit
    @line = Line.find(params[:id])
  end

  def update
    @line = Line.find(params[:id])
    @line.stations = []
    params[:line][:station_ids].each do |station|
      if station != ""
        @line.stations << Station.find(station)
      end
    end
    if @line.update(line_params)
      flash[:notice] = "Line updated."
      redirect_to line_path(@line)
    else
      render 'edit'
    end
  end

  def destroy
    @line = Line.find(params[:id])
    Stop.destroy_all(:line_id => @line.id)
    @line.destroy
    flash[:notice] = "Line deleted."
    redirect_to lines_path
  end

  private
  def line_params
    params.require(:line).permit(:name, :station_id, station_ids: [])
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Station created."
      redirect_to stations_path
    else
      render 'new'
    end
  end

  def show
    @station = Station.find(params[:id])
    @stops = Stop.where(station_id: @station.id)
  end

  def edit
    @station = Station.find(params[:id])
  end

  def update
    @station = Station.find(params[:id])
    if @station.update(station_params)
      flash[:notice] = "Station updated."
      redirect_to station_path(@station)
    else
      render 'edit'
    end
  end

  def destroy
    @station = Station.find(params[:id])
    Stop.destroy_all(:station_id => @station.id)
    @station.destroy
    flash[:notice] = "Station deleted."
    redirect_to stations_path
  end

private
  def station_params
    params.require(:station).permit(:name, :line_id, line_ids: [])
  end


end

app/controllers/stops_controller.rb
class StopsController < ApplicationController
  def index
    @stops = Stop.all
  end

  def new
    @stop = Stop.new
  end

  def create
    @stop = Stop.new(stop_params)
    if @stop.save
      flash[:notice] = "Stop created."
      redirect_to stops_path
    else
      flash[:alert] = "Please put stuff in properly."
      render 'new'
    end
  end

  def show
    @stop = Stop.find(params[:id])
    @station = Station.find(@stop.station_id)
    @line = Line.find(@stop.line_id)
  end

  def edit
    @stop = Stop.find(params[:id])
  end

  def update
    @stop = Stop.find(params[:id])
    if @stop.update(stop_params)
      flash[:notice] = "Stop updated."
      redirect_to stops_path
    else
      flash[:alert] = "Please put stuff in properly."
      render 'edit'
    end
  end

  def destroy
    @stop = Stop.find(params[:id])
    @stop.destroy
    flash[:notice] = "Stop deleted."
    redirect_to stops_path
  end

  private
  def stop_params
    params.require(:stop).permit(:station_id, :line_id, :time, line_ids: [], station_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timetable</title>
  <link rel="stylesheet" href="http://cdn.graphalchemist.com/alchemy.min.css">
  <script type="text/javascript" src="http://cdn.graphalchemist.com/alchemy.min.js">
  <link rel="stylesheet" type="text/css" href="path/to/vendor.css">
  <link rel="stylesheet" href="path/to/alchemy.css">
  <script type="text/javascript" src="path/to/vendor.js">
  <script type="text/javascript" src="path/to/alchemy.js">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">

  <% if flash[:notice] %>
    <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
  <% end %>
    <% if flash[:alert] %>
  <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
  <% end %>
  <%= yield %>
  <hr>
  <%= link_to "Home", stations_path, :class=> "btn btn-primary" %>
</div>
</body>
</html>

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/lines/edit.html.erb
<h1> Edit a Line </h1>

<hr>

<%= render 'form' %>

app/views/lines/index.html.erb
<h1>Lines</h1>

<ul>
  <% @lines.each do |line| %>
    <%= link_to "#{line.name}", line_path(line), :class=> "btn btn-default btn-sm" %>
  <% end %>
</ul>

<%= link_to "New Line", new_line_path, :class=> "btn btn-success" %>
<%= link_to "Stops", stops_path, :class=> "btn btn-info" %>
<%= link_to "Stations", stations_path, :class=> "btn btn-warning" %>

app/views/lines/new.html.erb
<h1> Add a Line </h1>

<hr>

<%= render 'form' %>

app/views/lines/show.html.erb
<h1><%= @line.name %></h1>

<% @stops.each do |stop| %>
  <div class="btn btn-default btn-sm">
    <%= "#{stop.find_station.name} - #{stop.time}"%>
  </div>
<% end %>

<div id="alchemy" class="alchemy" style="width: 300px; height:300px">
  <script>

      var limit = <%= Station.all.length %>;
      var nodes = [];
      for (i=1;i<=limit;i++) {
        nodes.push({"id": i});
      }
      var edges = [];
      for (i=1;i<limit;i++) {
        edges.push({"source": i, "target": (i+1)});
      }
      var some_data =
        {
          "nodes": nodes,
          "edges": edges
        };
  </script>
</div>
<script>alchemy.begin({"dataSource": some_data})</script>

<hr>
<%= link_to "Add Stops", new_stop_path, :class=> "btn btn-info" %>
<%= link_to "Edit Line", edit_line_path(@line), :class=> "btn btn-success" %>

<%= link_to "Delete", line_path(@line),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"},
                         :class => "btn btn-danger" %>

app/views/stations/_form.html.erb
<%= form_for(@station) do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/stations/edit.html.erb
<h1> Edit a Station </h1>

<hr>

<%= render 'form' %>

app/views/stations/index.html.erb
<h1>Stations</h1>

<ul>
  <% @stations.each do |station| %>
    <%= link_to "#{station.name}", station_path(station), :class=> "btn btn-default btn-sm" %>
  <% end %>
</ul>
<%= javascript_include_tag "colorparagraph.js" %>

<p>Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb. </p>

<p>Do you see any Teletubbies in here? Do you see a slender plastic tag clipped to my shirt with my name printed on it? Do you see a little Asian child with a blank expression on his face sitting outside on a mechanical helicopter that shakes when you put quarters in it? No? Well, that's what you see at a toy store. And you must think you're in a toy store, because you're here shopping for an infant named Jeb. </p>


<%= link_to "New Station", new_station_path, :class=> "btn btn-success" %>
<%= link_to "Lines", lines_path, :class=> "btn btn-danger" %>
<%= link_to "Stops", stops_path, :class=> "btn btn-info" %>

app/views/stations/new.html.erb
<h1> Add a Station </h1>

<hr>

<%= render 'form' %>

app/views/stations/show.html.erb
<h1><%= @station.name %></h1>
<ul>
  <% @stops.each do |stop| %>
    <%= link_to "#{stop.find_line.name} - #{stop.time}", edit_stop_path(stop), :class=> "btn btn-default btn-sm" %>
  <% end %>
</ul>

<%= link_to "Edit Station", edit_station_path(@station), :class=> "btn btn-success" %>

<%= link_to "Delete", station_path(@station),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"},
                         :class => "btn btn-danger" %>

app/views/stops/_form.html.erb
<%= form_for(@stop) do |f| %>
  <div class="form-group">
    <%= f.label "Station:" %>
    <%= f.collection_select :station_id, Station.all, :id, :name %>
  </div>
    <span><strong> connects to </strong></span>
  <div class="form-group">
    <%= f.label "Line:" %>
    <%= f.collection_select :line_id, Line.all, :id, :name %>
  </div>
  <div class="form-group">
  <%= f.label :time %>
  <%= f.text_field :time %>
  </div>
  <%= f.submit(:class => "btn btn-danger") %>
<% end %>

app/views/stops/edit.html.erb
<h1> Edit a Stop </h1>

<hr>

<%= render 'form' %>

app/views/stops/index.html.erb
<h1>Stops</h1>

<ul>
  <% @stops.each do |stop| %>
    <%= link_to "#{stop.find_station.name}", edit_stop_path(stop), :class=> "btn btn-default btn-sm" %>
  <% end %>
</ul>

<%= link_to "New Stop", new_stop_path, :class=> "btn btn-success" %>
<%= link_to "Lines", lines_path, :class=> "btn btn-danger" %>
<%= link_to "Stations", stations_path, :class=> "btn btn-warning" %>

app/views/stops/new.html.erb
<h1> Add a Stop </h1>

<hr>

<%= render 'form' %>

app/views/stops/show.html.erb
<h1><%= @station.name %></h1>

<%= link_to "Edit Stop", edit_stop_path(@stop), :class=> "btn btn-success" %>

<%= link_to "Delete", stop_path(@stop),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"},
                         :class => "btn btn-danger" %>